### PR TITLE
Backend/FixAddGroupsToSemester

### LINKED ISSUE #85: Wrong update of Semester groups

### PR DESCRIPTION
**Pull request by PavloLuchyk**
Fixed addGroupsToSemester method and removed redundant methods from SemesterService and SemesterController

Now addGroupsToSemester can add and remove Semester's groups

### CODE REVIEW

File: src/main/java/com/softserve/controller/SemesterController.java [hunk 1]
```diff
@@ -120,20 +120,10 @@ public ResponseEntity delete(@PathVariable("id") long id){
...
-
-    @DeleteMapping("/semesters/{semesterId}/groups")
-    @ApiOperation(value = "Delete groups from semester by id")
-    public ResponseEntity<SemesterWithGroupsDTO> deleteGroupsFromSemester(@PathVariable Long semesterId, @RequestParam Long[] groupId) {
-        log.info("In deleteGroupsFromSemester (semesterId = [{}], groupId = [{}])", semesterId, groupId);
-        List<Group> groups = groupService.getGroupsByGroupIds(groupId);
-        Semester semester = semesterService.deleteGroupsFromSemester(semesterService.getById(semesterId), groups);
+    @ApiOperation(value = "Replace groups in semester by id")
+    public ResponseEntity<SemesterWithGroupsDTO> addGroupsToSemester(@PathVariable Long semesterId, @RequestBody Long[] groupId) {
+        log.trace("In addGroupsToSemester (semesterId = [{}], groupId = [{}])", semesterId, groupId);
```
Comment (yuremboo) [inline src/main/java/com/softserve/controller/SemesterController.java]: info
and also try to do array toString, and let me know if it is very informative :)

File: src/main/java/com/softserve/controller/SemesterController.java [hunk 2]
```diff
@@ -120,20 +120,10 @@ public ResponseEntity delete(@PathVariable("id") long id){
...
-    }
-
-    @DeleteMapping("/semesters/{semesterId}/groups")
-    @ApiOperation(value = "Delete groups from semester by id")
-    public ResponseEntity<SemesterWithGroupsDTO> deleteGroupsFromSemester(@PathVariable Long semesterId, @RequestParam Long[] groupId) {
-        log.info("In deleteGroupsFromSemester (semesterId = [{}], groupId = [{}])", semesterId, groupId);
-        List<Group> groups = groupService.getGroupsByGroupIds(groupId);
-        Semester semester = semesterService.deleteGroupsFromSemester(semesterService.getById(semesterId), groups);
+    @ApiOperation(value = "Replace groups in semester by id")
+    public ResponseEntity<SemesterWithGroupsDTO> addGroupsToSemester(@PathVariable Long semesterId, @RequestBody Long[] groupId) {
```
Comment (yuremboo) [inline src/main/java/com/softserve/controller/SemesterController.java]: Why not List<Long> ?

**Review by yuremboo — CHANGES_REQUESTED** [review]
