### PR TITLE
Bug-190

### LINKED ISSUE #190: Incorrect update grouped Lesson with different subject_for_site
1. Create two grouped lessons with same Teacher and Subject, but with different Subject_for_site for different groups
Test Data: 
Teacher: Бигар Ганна Павлівна (доцент), Subject: Frontend-розробка Web-додатків LessonType: Лекція, Hours: 1, Grouped: true, SubjectForSite: Frontend-розробка Web-додатків 1, Groups: 11(101-A), 13(111-A)
Teacher: Бигар Ганна Павлівна (доцент), Subject: Frontend-розробка Web-додатків LessonType: Лекція, Hours: 1, Grouped: true, SubjectForSite: Frontend-розробка Web-додатків 2, Groups: 12(101-Б), 13(111-Б)
2. Update second lesson, change SubjectForSite to - Frontend-розробка Web-додатків 3

**Expected result:**
Change SubjectForSite only for Groups: 12(101-Б), 13(111-Б)
**Actual result:**
Change SubjectForSite for Groups: 11(101-A), 13(111-A) 12(101-Б), 13(111-Б)
**Post condition:** 
Delete created lessons for Groups: 11(101-A), 13(111-A) 12(101-Б), 13(111-Б)

### PR DESCRIPTION
**Pull request by SaneQQQQ**

### CODE REVIEW

File: src/main/java/com/softserve/dto/LessonBaseDTO.java [hunk 1]
```diff
@@ -17,6 +17,6 @@
     private String subjectForSite;
     private LessonType lessonType;
     private SubjectDTO subject;
-    private TeacherDTO teacher;
+    private TeacherNameDTO teacher;
```
Comment (dshma) [inline src/main/java/com/softserve/dto/LessonBaseDTO.java]: why change this?

File: src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java [hunk 2]
```diff
@@ -30,20 +30,36 @@
...
+            + " subjectForSite = :subjectForSite, "
+            + " linkToMeeting = :linkToMeeting "
             + "where grouped = true "
             + "and subject.id = :initialSubjectId "
             + "and hours = :initialHours "
             + "and teacher.id = :initialTeacherId "
             + "and semester.id = :initialSemesterId "
-            + "and lessonType = :initialLessonType";
+            + "and lessonType = :initialLessonType "
+            + "and subjectForSite = :initialSubjectForSite";
```
Comment (dshma) [inline src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java:60]: The only dissimilarity between these 2 queries is this line. Why not keep only one query?

File: src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java [hunk 3]
```diff
@@ -320,21 +336,27 @@ public Integer updateLinkToMeeting(Lesson lesson) {
...
                 .setParameter("initialLessonType", oldLesson.getLessonType())
+                .setParameter("linkToMeeting", updatedLesson.getLinkToMeeting())
                 .setParameter("subjectId", updatedLesson.getSubject().getId())
                 .setParameter("hours", updatedLesson.getHours())
                 .setParameter("teacherId", updatedLesson.getTeacher().getId())
                 .setParameter("lessonType", updatedLesson.getLessonType())
-                .setParameter("subjectForSite", updatedLesson.getSubjectForSite())
-                .executeUpdate();
+                .setParameter("subjectForSite", updatedLesson.getSubjectForSite());
+        query = isTeacherOrSubjectUpdated
```
Comment (dshma) [inline src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java:352]: This does seem odd to me, 2 different queries are being executed hinging on one parameter? How is it different from initialHours/initialLessonType?

File: src/test/java/com/softserve/controller/LessonsControllerTest.java [hunk 4]
```diff
@@ -153,6 +154,95 @@ public void updateLessonIfLessonDoesNotExist() throws Exception {
...
+                .andExpect(jsonPath("$.subject").value(expectedLesson.getSubject()))
+                .andExpect(jsonPath("$.teacher").value(expectedLesson.getTeacher()))
+                .andExpect(jsonPath("$.group").value(expectedLesson.getGroup()))
+                .andExpect(jsonPath("$.grouped").value(expectedLesson.isGrouped()));
+
+        Lesson GroupedWithSameSubjectForSite = lessonService.getById(14L);
+        Lesson GroupedWithDiffSubjectForSite = lessonService.getById(15L);
+
+        SoftAssertions softAssertions = new SoftAssertions();
+        softAssertions.assertThat(expectedLesson).isEqualToComparingOnlyGivenFields(GroupedWithSameSubjectForSite,
```
Comment (dshma) [inline src/test/java/com/softserve/controller/LessonsControllerTest.java:188]: What are the conditions (parameters) that differ grouped lessons? In other words, what might be different and should be identical about 2 grouped lessons?

File: src/main/java/com/softserve/service/impl/LessonServiceImpl.java [hunk 5]
```diff
@@ -155,7 +155,11 @@ public Lesson update(Lesson lesson) {
             if (!oldLesson.isGrouped()) {
                 lessonRepository.setGrouped(lesson.getId());
             }
-            lesson =  lessonRepository.updateGrouped(oldLesson, lesson);
+            boolean isTeacherOrSubjectUpdated = ((oldLesson.getSubject().getId().longValue()
```
Comment (dshma) [inline src/main/java/com/softserve/service/impl/LessonServiceImpl.java]: better to extract some conditions into local variables

**Review by dshma — CHANGES_REQUESTED** [review]

File: src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java (hunk 2 above)
Comment (SaneQQQQ) [reply src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java:60]: Because we need two different behaviors. We can create many grouped lessons with the same pair(Subject & Teacher). They are grouping about SubjectForSite parameter. When we update Subject or Teacher - we need to change all the grouped lessons with pair(Subject & Teacher). When we change the rest of parameters (any parameters without Subject or Teacher) we need to change only one lesson, without change another grouped lessons.

File: src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java (hunk 3 above)
Comment (SaneQQQQ) [reply src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java:352]: No difference. I delete initialHours and InitialLessonType from UPDATE_GROUPED_TEACHER_OR_SUBJECT

File: src/test/java/com/softserve/controller/LessonsControllerTest.java (hunk 4 above)
Comment (SaneQQQQ) [reply src/test/java/com/softserve/controller/LessonsControllerTest.java:188]: SubjectForSite parameter

File: src/main/java/com/softserve/dto/LessonBaseDTO.java (hunk 1 above)
Comment (SaneQQQQ) [reply src/main/java/com/softserve/dto/LessonBaseDTO.java]: There' s no need to use TeacherDTO. I should change it in separate task

**Review by dshma — APPROVED** [review]
