### PR TITLE
Fix incorrect data types for 

### LINKED ISSUE #199: Fix incorrect data types for ID

### PR DESCRIPTION
**Pull request by vchornyy12**

### CODE REVIEW

File: src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ private Session getSession(){
      * @param entity Semester is going to be updated
      * @return Semester
      */
-    @Override
+    @Override //merge?
```
Comment (dshma) [inline src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java]: why is this being left here?

File: src/main/java/com/softserve/service/impl/UserServiceImpl.java [hunk 2]
```diff
@@ -284,7 +285,7 @@ private User registration(User user, String registrationMessage) {
             String token = UUID.randomUUID().toString();
             user.setToken(token);
             User registrationUser = save(user);
-            sendRegistrationMail(user, registrationMessage);
+//            sendRegistrationMail(user, registrationMessage);
```
Comment (dshma) [inline src/main/java/com/softserve/service/impl/UserServiceImpl.java]: no way this is getting committed

**Review by dshma — CHANGES_REQUESTED** [review]

**Comment by dshma** [comment]
Do make sure the changelogs are up to date after these changes.

**Comment by vchornyy12** [comment]
Changing data types into Long has no influence on tables creation

File: src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java (hunk 1 above)
Comment (vchornyy12) [reply src/main/java/com/softserve/repository/impl/SemesterRepositoryImpl.java]: All comments are removed from this file

File: frontend/.eslintrc.json [hunk 3]
```diff
@@ -1,62 +0,0 @@
-{
```
Comment (dshma) [inline frontend/.eslintrc.json:1]: why have you removed this file?

File: src/main/java/com/softserve/service/impl/UserServiceImpl.java (hunk 2 above)
Comment (vchornyy12) [reply src/main/java/com/softserve/service/impl/UserServiceImpl.java]: row 288 is uncommented

**Review by dshma — CHANGES_REQUESTED** [review]

File: frontend/.eslintrc.json (hunk 3 above)
Comment (vchornyy12) [reply frontend/.eslintrc.json:1]: This file was removed together with autogenerated package-lock.json because of some conflicts of ESlint's plugins versions in the package.json file (by restoring Schedule application locally on Intellij Idea). After resolving conflicts this file should be in the repository. So, removing of .eslintrc.json was commited accidentally.

**Review by dshma — APPROVED** [review]
