### PR TITLE
Backend/FixGroupLessonUpdate

### LINKED ISSUE #93: Wrong group lesson update/delete
Group lessons is not updating properly, only one is getting updated. Same with delete

### PR DESCRIPTION
**Pull request by PavloLuchyk**
[93][BE] Updated LessonRepository to update group lessons properly

### CODE REVIEW

File: src/main/java/com/softserve/mapper/LessonInfoMapper.java [hunk 1]
```diff
@@ -26,7 +27,7 @@
             LessonInfoDTO lessonInfoDTO = new LessonInfoDTO();
```
Comment (yuremboo) [inline src/main/java/com/softserve/mapper/LessonInfoMapper.java]: Why don't you use mapstruct conversion here?

File: src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java [hunk 2]
```diff
@@ -259,4 +310,51 @@ public Integer updateLinkToMeeting(Lesson lesson) {
...
+    /**
+     * Method is used to update grouped lessons
+     * @param updatedLesson grouped lesson that needs to be updated
+     * @return updated Lesson
+     */
+    @Override
+    public Lesson updateGrouped(Lesson updatedLesson) {
+        log.info("Entered updateGroup({})", updatedLesson);
+        Lesson oldLesson = findById(updatedLesson.getId())
+                .orElseThrow(() -> new EntityNotFoundException(Lesson.class, "id", updatedLesson.getId().toString()));
```
Comment (yuremboo) [inline src/main/java/com/softserve/repository/impl/LessonRepositoryImpl.java]: It'd be better to search old lesson on service side, and send already updated data to repo. So that in repo should be 1 method - 1 query

File: src/main/java/com/softserve/service/impl/LessonServiceImpl.java [hunk 3]
```diff
@@ -21,7 +21,7 @@
 import java.util.List;
 
 @Slf4j
-@Transactional
+@Transactional(readOnly = true)
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/LessonServiceImpl.java]: you can remove @Transactional from class and use it only for methods, it will be more clear. but this is just advice

**Review by yuremboo — CHANGES_REQUESTED** [review]
