### PR TITLE
Bug-192

### LINKED ISSUE #192: Incorrect delete grouped Lesson with different subject_for_site
1. Create two grouped lessons with same Teacher and Subject, but with different Subject_for_site for different groups
Test Data: 
Teacher: Бигар Ганна Павлівна (доцент), Subject: Frontend-розробка Web-додатків LessonType: Лекція, Hours: 1, Grouped: true, SubjectForSite: Frontend-розробка Web-додатків 1, Groups: 11(101-A), 13(111-A)
Teacher: Бигар Ганна Павлівна (доцент), Subject: Frontend-розробка Web-додатків LessonType: Лекція, Hours: 1, Grouped: true, SubjectForSite: Frontend-розробка Web-додатків 2, Groups: 12(101-Б), 13(111-Б)
2. Delete second lesson

**Expected result:**
Delete Lesson for Groups: 12(101-Б), 13(111-Б)
**Actual result:**
Delete Lesson for Groups: 11(101-A), 13(111-A) 12(101-Б), 13(111-Б)
**Post condition:** 
Delete created lessons for Groups: 11(101-A), 13(111-A) 12(101-Б), 13(111-Б)

### PR DESCRIPTION
**Pull request by SaneQQQQ**

### CODE REVIEW

File: src/test/java/com/softserve/controller/LessonsControllerTest.java [hunk 1]
```diff
@@ -160,6 +167,16 @@ public void deleteLesson() throws Exception {
                 .andExpect(status().isOk());
     }
 
+    @Test
+    public void deleteLessonGrouped() throws Exception {
```
Comment (dshma) [inline src/test/java/com/softserve/controller/LessonsControllerTest.java:171]: avoid throws Exception, you should know the exceptions you're expecting under various circumstances

File: src/test/resources/create-lessons-before.sql [hunk 2]
```diff
@@ -60,4 +61,10 @@ insert into "public".lessons(id, hours, lessontype, subject_for_site, link_to_me
...
 (11, 1, 'PRACTICAL', '', '', 7, 5, 5, 5),
-(12, 1, 'PRACTICAL', '', '', 5, 5, 5, 5);
\ No newline at end of file
+(12, 1, 'PRACTICAL', '', '', 5, 5, 5, 5);
+
+insert into "public".lessons(id, hours, lessontype, subject_for_site, link_to_meeting, semester_id, group_id, subject_id, teacher_id, grouped) VALUES
+(13, 1, 'LECTURE', 'Frontend-розробка Web-додатків 1', '', 5, 4, 4, 5, true),
+(14, 1, 'LECTURE', 'Frontend-розробка Web-додатків 1', '', 5, 5, 4, 5, true),
+(15, 1, 'LECTURE', 'Frontend-розробка Web-додатків 2', '', 5, 6, 4, 5, true),
+(16, 1, 'LECTURE', 'Frontend-розробка Web-додатків 2', '', 5, 7, 4, 5, true);
```
Comment (dshma) [inline src/test/resources/create-lessons-before.sql]: why is this record required if it's not being used in the test?

**Review by dshma — CHANGES_REQUESTED** [review]

File: src/test/resources/create-lessons-before.sql (hunk 2 above)
Comment (SaneQQQQ) [reply src/test/resources/create-lessons-before.sql]: Changed

**Review by dshma — APPROVED** [review]
