### PR TITLE
[Backend]fix copy semester, and add Test

### LINKED ISSUE #90: Fix copySemester

### PR DESCRIPTION
**Pull request by IuriiMocherniuk**
Deleted old EndPoint copySchedule
Added new EndPoin copySemester
Changed log in public methods from info to debug  in SemesterServiceImpl.java
Created new methods addDaysOfWeekToSemester , addPeriodsToSemester, deleteAllContentFromSemester, copyLesson, copySchedule

Added Test

### CODE REVIEW

File: src/main/java/com/softserve/controller/SemesterController.java [hunk 1]
```diff
@@ -24,13 +31,21 @@
 @Slf4j
 public class SemesterController {
 
+    private final GroupRepository groupRepository;
```
Comment (yuremboo) [inline src/main/java/com/softserve/controller/SemesterController.java]: Avoid calling Repository from controller

File: src/main/java/com/softserve/service/impl/UserServiceImpl.java [hunk 2]
```diff
@@ -282,7 +282,7 @@ private User registration(User user, String registrationMessage) {
             String token = UUID.randomUUID().toString();
             user.setToken(token);
             User registrationUser = save(user);
-            sendRegistrationMail(user, registrationMessage);
+            /*sendRegistrationMail(user, registrationMessage);*/
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/UserServiceImpl.java]: Avoid commented code

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 3]
```diff
@@ -44,7 +48,7 @@ public SemesterServiceImpl(SemesterRepository semesterRepository, PeriodService
      */
     @Override
     public Semester getById(Long id) {
-        log.info("In getById(id = [{}])", id);
+        log.debug("In getById(id = [{}])", id);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: this is useful can be info

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 4]
```diff
@@ -60,14 +64,14 @@ public Semester getById(Long id) {
      */
     @Override
     public List<Semester> getAll() {
-        log.info("In getAll()");
+        log.debug("In getAll()");
         List<Semester> semesters = semesterRepository.getAll();
-        for (Semester semester:semesters) {
+        for (Semester semester : semesters) {
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java:76]: Update query for this method to fetch in one shot instead of using Hibernate.initialize like "JOIN FETCH"

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 5]
```diff
@@ -78,7 +82,7 @@ public Semester getById(Long id) {
      */
     @Override
     public Semester save(Semester semester) {
-        log.info("In save(entity = [{}]", semester);
+        log.debug("In save(entity = [{}]", semester);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: useful log

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 6]
```diff
@@ -198,40 +207,55 @@ public Semester getDefaultSemester() {
...
-        log.info("Enter into isTimeInvalid  with entity: {}", object);
+        log.debug("Enter into isTimeInvalid  with entity: {}", object);
         return object.getStartDay().isAfter(object.getEndDay()) ||
                 object.getStartDay().equals(object.getEndDay());
     }
 
-    private boolean isSemesterExists(long semesterId, String description, int year){
-        log.info("In isSemesterExists (semesterId = [{}],description = [{}], year = [{}])", semesterId, description, year);
+    private boolean isSemesterExists(long semesterId, String description, int year) {
+        log.debug("In isSemesterExists (semesterId = [{}],description = [{}], year = [{}])", semesterId, description, year);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: useful

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 7]
```diff
@@ -198,40 +207,55 @@ public Semester getDefaultSemester() {
...
+     * The method is used for checking if semester with schedule are not removed from the updated semester
+     *
+     * @param semester that is checked before updating
+     * @return true if schedule have been removed from the updated semester;
+     * false if schedule have not been removed.
+     */
+    private boolean isScheduleWithLessonsCanNotBeRemoved(Semester semester) {
+        log.debug("Enter into isScheduleWithLessonsCanNotBeRemoved with entity: {}", semester);
+        List<Schedule> scheduleInSemester = scheduleRepository.getScheduleBySemester(semester.getId());
+        return !scheduleRepository.getScheduleBySemester(semester.getId()).containsAll(scheduleInSemester);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: scheduleRepository.getScheduleBySemester already called above

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 8]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+        log.debug("In addDaysOfWeekToSemester (semester = [{}], daysOfWeek = [{}])", semester, daysOfWeek);
+
+        Set<DayOfWeek> days = semester.getDaysOfWeek();
+
+        if (days == null) {
+            days = new HashSet<DayOfWeek>();
+        }
+        days.addAll(daysOfWeek);
+        semester.setDaysOfWeek(days);
+        getById(semester.getId()).setDaysOfWeek(days);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: why do you need this line?
>getById(semester.getId()).setDaysOfWeek(days);

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 9]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+        log.debug("In addPeriodsToSemester (semester = [{}], periods = [{}])", semester, periods);
+
+        Set<Period> periodsSemester = semester.getPeriods();
+
+        if (periodsSemester == null) {
+            periodsSemester = new HashSet<Period>();
+        }
+        periodsSemester.addAll(periods);
+        semester.setPeriods(periodsSemester);
+        getById(semester.getId()).setPeriods(periodsSemester);
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: And this

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 10]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+    /**
+     * Method copy groups, periods, days Of Weeks and Schedule from one to other semester
+     *
+     * @param fromSemesterId id semester from which we need to copy groups, periods, days Of Weeks and Schedule
+     * @param toSemesterId   id semester in which we need to copy groups, periods, days Of Weeks and Schedule
+     * @return copied Semester
+     */
+    @Override
+    public Semester copySemester(Long fromSemesterId, Long toSemesterId) {
+
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: please add log

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 11]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+        Semester toSemester = getById(toSemesterId);
+        Semester fromSemester = getById(fromSemesterId);
+        List<Schedule> schedules = scheduleRepository.getScheduleBySemester(fromSemesterId);
+        for (Schedule schedule : schedules) {
+            Hibernate.initialize(schedule.getLesson().getSemester().getDaysOfWeek());
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: please, fetch always with data that you need. Use JOIN FETCH

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 12]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+            Hibernate.initialize(schedule.getLesson().getSemester().getPeriods());
+            Hibernate.initialize(schedule.getLesson().getSemester().getGroups());
+        }
+
+        List<Group> groups = getById(toSemesterId).getGroups();
+        Set<Period> periods = toSemester.getPeriods();
+        Set<DayOfWeek> dayOfWeeks = toSemester.getDaysOfWeek();
+
+        if (!groups.isEmpty() || !periods.isEmpty() || !dayOfWeeks.isEmpty()) {
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Get use to use such lib as Apache Commons and Apache Collections for such simple scenarios. https://www.baeldung.com/apache-commons-collection-utils

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 13]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+            oldToNewLessonMap.put(lesson, lessonNewSaved);
+        }
+
+        for (Schedule schedule : schedules) {
+             scheduleRepository.save(copySchedule(schedule, oldToNewLessonMap.get(schedule.getLesson())));
+        }
+        return toSemester;
+    }
+
+    private Lesson copyLesson(Lesson lesson, Semester toSemester) {
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Can be replaced with MapStruct

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java [hunk 14]
```diff
@@ -301,49 +326,178 @@ public Semester addGroupToSemester(Semester semester, Group group) {
...
+        lessonNew.setSubjectForSite(lesson.getSubjectForSite());
+        lessonNew.setGroup(lesson.getGroup());
+        lessonNew.setSubject(lesson.getSubject());
+        lessonNew.setTeacher(lesson.getTeacher());
+        lessonNew.setGrouped(lesson.isGrouped());
+        lessonNew.setLinkToMeeting(lesson.getLinkToMeeting());
+        return lessonNew;
+    }
+
+    private Schedule copySchedule (Schedule schedule, Lesson lesson){
```
Comment (yuremboo) [inline src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Can be replaced with MapStruct

**Review by yuremboo — CHANGES_REQUESTED** [review]

File: src/main/java/com/softserve/controller/SemesterController.java (hunk 1 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/controller/SemesterController.java]: Done

File: src/main/java/com/softserve/service/impl/UserServiceImpl.java (hunk 2 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/UserServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 3 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 5 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 10 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 13 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 14 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 12 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: still in the process

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 11 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: The Hibernate.initialize approach is applied throughout the project, example in LessonServiceImpl and ScheduleServiceImpl.
Maybe it's worth creating a separate task to fix the whole project?

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 4 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java:76]: The Hibernate.initialize approach is applied throughout the project, example in LessonServiceImpl and ScheduleServiceImpl.
Maybe it's worth creating a separate task to fix the whole project?

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 6 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 7 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 8 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 9 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 12 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 4 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java:76]: Done

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 11 above)
Comment (IuriiMocherniuk) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java]: Done

**Review by yuremboo — APPROVED** [review]

File: src/main/java/com/softserve/service/impl/SemesterServiceImpl.java (hunk 4 above)
Comment (yuremboo) [reply src/main/java/com/softserve/service/impl/SemesterServiceImpl.java:76]: I still see hibernate initialize here :)

**Review by yuremboo — CHANGES_REQUESTED** [review]
